language: c++
sudo: required
services: docker
install:
- docker pull devkitpro/devkitarm
script:
- docker run -e ENABLE_COMPATIBILITY_REPORTING -v $TRAVIS_BUILD_DIR:/GameOfLife-3DS-ClubMatrix
  devkitpro/devkitarm /bin/bash -ex /GameOfLife-3DS-ClubMatrix/.travis/build.sh
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: <TODO>
  file: GameOfLife-3DS-ClubMatrix.3dsx
  on:
      tags: true
env:
  global:
    secure: <TODO>
